# GET https://qiita.com/api/v2/users/TakahiRoyte
# GET https://data.rcsb.org/rest/v1/core/entry/1ELC/1
# GET https://data.rcsb.org/rest/v1/core/polymer_entity/1ELC/1

# https://data.rcsb.org/graphql?query={entry(entry_id:"4HHB"){exptl{method}}}


https://data.rcsb.org/graphql?query={entry(entry_id:"4HHB"){nonpolymer_entities {rcsb_nonpolymer_entity_container_identifiers {entry_id}nonpolymer_comp {chem_comp {idtypeformula_weightformula}rcsb_chem_comp_descriptor {InChIInChIKey}pdbx_chem_comp_descriptor {descriptortypeprogram}}}}}
